package models

import (
	"fmt"
	"time"
)

// BaseModel contains fields common to all database records.
// Embedded in User and Profile structs.
type BaseModel struct {
	ID        string    `json:"id"`         // UUID generated by PostgreSQL
	CreatedAt time.Time `json:"created_at"` // Set automatically on INSERT
	UpdatedAt time.Time `json:"updated_at"` // Updated automatically on UPDATE
}

// User represents a registered sub user account in the users table.
// Main users are NOT stored here — they use hardcoded credentials.
type User struct {
	BaseModel
	Email        string `json:"email"`
	PasswordHash string `json:"-"` // Never sent to client
	FullName     string `json:"full_name"`
	Phone        string `json:"phone,omitempty"`
	IsActive     bool   `json:"is_active"`
}

// Profile represents a profile record in the profiles table.
// Both main profiles (is_main_profile=true) and sub user profiles
// (is_main_profile=false) are stored here.
type Profile struct {
	BaseModel
	UserID             string     `json:"user_id"`
	Name               string     `json:"name"`
	Email              string     `json:"email,omitempty"`
	Phone              string     `json:"phone,omitempty"`
	ProfilePictureURL  string     `json:"profile_picture_url,omitempty"`
	CoverPhotoURL      string     `json:"cover_photo_url,omitempty"`
	Bio                string     `json:"bio,omitempty"`
	Age                int        `json:"age,omitempty"`
	Gender             string     `json:"gender,omitempty"`
	YearLevel          string     `json:"year_level,omitempty"`
	Birthday           *time.Time `json:"birthday,omitempty"` // Pointer so null birthday works
	Hometown           string     `json:"hometown,omitempty"`
	RelationshipStatus string     `json:"relationship_status,omitempty"`
	Education          string     `json:"education,omitempty"`
	Work               string     `json:"work,omitempty"`
	Interests          []string   `json:"interests"`
	IsMainProfile      bool       `json:"is_main_profile"`
	MainProfileID      *string    `json:"main_profile_id,omitempty"`
}

// RegisterRequest is the expected body for POST /api/auth/register.
type RegisterRequest struct {
	FullName string `json:"full_name" binding:"required"`
	Email    string `json:"email" binding:"required,email"`
	Password string `json:"password" binding:"required,min=8"`
	Phone    string `json:"phone"`
}

// LoginRequest is the expected body for POST /api/auth/login.
type LoginRequest struct {
	Email    string `json:"email" binding:"required,email"`
	Password string `json:"password" binding:"required"`
}

// AuthResponse is returned after successful login or registration.
// Contains the JWT token and user identity information.
// The role field ("main" or "sub") controls all UI permissions in Flutter.
type AuthResponse struct {
	Token string `json:"token"`          // JWT token for subsequent requests
	Role  string `json:"role"`           // "main" or "sub"
	Email string `json:"email"`          // User's email address
	Name  string `json:"name"`           // Display name
	User  *User  `json:"user,omitempty"` // Full user record (sub users only)
}

// FlexibleDate is a custom time.Time that accepts multiple date formats.
//
// WHY THIS EXISTS:
// Flutter's DateTime.toIso8601String() produces "2003-05-15T00:00:00.000"
// which is missing the timezone suffix Go expects ("Z" or "+07:00").
// This caused the "cannot parse as z07:00" error.
//
// FIX: We send date-only strings from Flutter ("2003-05-15")
// and this type tries multiple formats until one parses successfully.
type FlexibleDate struct {
	time.Time
}

// UnmarshalJSON implements the json.Unmarshaler interface for FlexibleDate.
// Tries multiple date formats so any reasonable date string will parse.
func (f *FlexibleDate) UnmarshalJSON(data []byte) error {
	str := string(data)

	// Remove surrounding JSON quotes
	if len(str) >= 2 {
		str = str[1 : len(str)-1]
	}

	// Treat null or empty as a zero/missing date
	if str == "null" || str == "" {
		return nil
	}

	// Try formats in order of likelihood
	layouts := []string{
		"2006-01-02",                // Date only from Flutter: "2003-05-15"
		time.RFC3339,                // Full RFC3339: "2003-05-15T00:00:00Z"
		"2006-01-02T15:04:05",       // Without timezone: "2003-05-15T00:00:00"
		"2006-01-02T15:04:05Z07:00", // With timezone offset
	}

	for _, layout := range layouts {
		if t, err := time.Parse(layout, str); err == nil {
			f.Time = t
			return nil
		}
	}

	// Return descriptive error instead of crashing
	return fmt.Errorf("cannot parse date: %s", str)
}

// CreateSubUserRequest is the expected body for POST /api/profiles/sub.
// Uses FlexibleDate for birthday to handle multiple date formats from Flutter.
type CreateSubUserRequest struct {
	Name               string        `json:"name" binding:"required"`
	Age                int           `json:"age"`
	Gender             string        `json:"gender"`
	YearLevel          string        `json:"year_level"`
	Bio                string        `json:"bio"`
	Birthday           *FlexibleDate `json:"birthday"` // FlexibleDate handles format variations
	Email              string        `json:"email"`
	Phone              string        `json:"phone"`
	Hometown           string        `json:"hometown"`
	RelationshipStatus string        `json:"relationship_status"`
	Education          string        `json:"education"`
	Work               string        `json:"work"`
	Interests          []string      `json:"interests"`
	ProfilePictureURL  string        `json:"profile_picture_url"` // May be base64 data URI
	CoverPhotoURL      string        `json:"cover_photo_url"`     // May be base64 data URI
	IsMainProfile      bool          `json:"is_main_profile"`
}

// UpdateProfileRequest is the expected body for PUT /api/profiles/:id.
// All fields are optional — only provided fields should be updated.
type UpdateProfileRequest struct {
	Name               string        `json:"name"`
	Bio                string        `json:"bio"`
	Age                int           `json:"age"`
	Gender             string        `json:"gender"`
	YearLevel          string        `json:"year_level"`
	Birthday           *FlexibleDate `json:"birthday"` // FlexibleDate handles format variations
	Hometown           string        `json:"hometown"`
	RelationshipStatus string        `json:"relationship_status"`
	Education          string        `json:"education"`
	Work               string        `json:"work"`
	Interests          []string      `json:"interests"`
	ProfilePictureURL  string        `json:"profile_picture_url"`
	CoverPhotoURL      string        `json:"cover_photo_url"`
	Email              string        `json:"email"`
	Phone              string        `json:"phone"`
}

// MainUserConfig holds credentials for one hardcoded main user.
// These users are NOT stored in the database.
// Authentication is done by direct comparison in auth_handler.go.
type MainUserConfig struct {
	ID       string // Fake UUID used in JWT token ("main-user-001")
	Email    string // Login email
	Password string // Plain text password (compared directly, not hashed)
	Name     string // Display name shown in the UI
}

// HardcodedMainUsers contains the 3 real main users of the system.
// These match the 3 profile cards shown on the main dashboard in Flutter.
// IMPORTANT: Passwords are stored in plain text here because main users
// don't have DB records. For production, consider using env variables.
var HardcodedMainUsers = []MainUserConfig{
	{
		ID:       "main-user-001",
		Email:    "pallen@main.com",
		Password: "Pallen@123",
		Name:     "Pallen, Prince Dunhill",
	},
	{
		ID:       "main-user-002",
		Email:    "karl@main.com",
		Password: "Karl@123",
		Name:     "Albaniel, Karl Angelo",
	},
	{
		ID:       "main-user-003",
		Email:    "aldhy@main.com",
		Password: "Aldhy@123",
		Name:     "Fajardo, Aldhy",
	},
}

// MainUserProfileMap maps a main user's hardcoded ID to their Flutter profile ID.
// Used in UpdateProfile to check if a main user is editing their own profile.
// The Flutter profile IDs (profile_1/2/3) match the local Dart model files.
var MainUserProfileMap = map[string]string{
	"main-user-001": "profile_1",
	"main-user-002": "profile_2",
	"main-user-003": "profile_3",
}

// MainProfiles contains the seed data for the 3 main profile records.
// These are inserted into the profiles table on first server startup.
// They are owned by the system user (system@localhost).
var MainProfiles = []Profile{
	{
		Name:               "Pallen, Prince Dunhill",
		Email:              "pallen@main.com",
		Phone:              "+63 912 345 6789",
		ProfilePictureURL:  "assets/images/default_avatar.png",
		CoverPhotoURL:      "assets/images/default_cover.png",
		Bio:                "Computer Science major | Photography enthusiast | Coffee lover ☕",
		Age:                21,
		Gender:             "Male",
		YearLevel:          "Junior",
		Hometown:           "Manila, Philippines",
		RelationshipStatus: "Single",
		Education:          "B.S. Computer Science",
		Work:               "Software Engineering Intern",
		Interests:          []string{"Photography", "Hiking", "Coding", "Reading", "Travel"},
		IsMainProfile:      true,
	},
	{
		Name:               "Albaniel, Karl Angelo",
		Email:              "karl@main.com",
		Phone:              "+63 923 456 7890",
		ProfilePictureURL:  "assets/images/default_avatar.png",
		CoverPhotoURL:      "assets/images/default_cover.png",
		Bio:                "Business Administration | Basketball player 🏀 | Aspiring entrepreneur",
		Age:                22,
		Gender:             "Male",
		YearLevel:          "Senior",
		Hometown:           "Cebu, Philippines",
		RelationshipStatus: "In a relationship",
		Education:          "B.B.A. Finance",
		Work:               "Investment Banking Analyst",
		Interests:          []string{"Basketball", "Stock Trading", "Golf", "Networking", "Music"},
		IsMainProfile:      true,
	},
	{
		Name:               "Fajardo, Aldhy",
		Email:              "aldhy@main.com",
		Phone:              "+63 934 567 8901",
		ProfilePictureURL:  "assets/images/default_avatar.png",
		CoverPhotoURL:      "assets/images/default_cover.png",
		Bio:                "Psychology major | Mental health advocate 🧠 | Yoga instructor",
		Age:                20,
		Gender:             "Male",
		YearLevel:          "Sophomore",
		Hometown:           "Davao, Philippines",
		RelationshipStatus: "Single",
		Education:          "B.A. Psychology",
		Work:               "Research Assistant",
		Interests:          []string{"Yoga", "Meditation", "Painting", "Volunteering", "Dancing"},
		IsMainProfile:      true,
	},
}
